export const POKEMON_TYPE = {
  bug: { label: 'Inseto', color: '#729f3f' },
  dark: { label: 'Sombrio', color: '#707070' },
  dragon: { label: 'Dragão', color: '#f16e57' },
  electric: { label: 'Eletrico', color: '#eed535' },
  fairy: { label: 'Fada', color: '#fdb9e9' },
  fighting: { label: 'Lutador', color: '#d56723' },
  fire: { label: 'Fogo', color: '#fd7d24' },
  flying: { label: 'Voador', color: '#3dc7ef' },
  ghost: { label: 'Fantasma', color: '#7b62a3' },
  grass: { label: 'Planta', color: '#9bcc50' },
  ground: { label: 'Terra', color: '#f7de3f' },
  ice: { label: 'Gelo', color: '#51c4e7' },
  normal: { label: 'Normal', color: '#a4acaf' },
  poison: { label: 'Venenoso', color: '#b97fc9' },
  psychic: { label: 'Psíquico', color: '#f366b9' },
  rock: { label: 'Pedra', color: '#a38c21' },
  shadow: { label: 'Sombrio', color: '#707070' },
  steel: { label: 'Aço', color: '#9eb7b8' },
  stellar: { label: 'Estelar', color: '#a38c21' },
  unknown: { label: 'Desconhecido', color: '#' },
  water: { label: 'Água', color: '#4592c4' },
};
